version: "3.8"
services:

  my-custom-springboot-app:
    image: springapplicationforfileoperation.jar
    ports:
      - "8080:8080"


  database:
    image: mongo:latest
    container_name: mongodb
    restart: always
